/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: 80ed7f8170837e0d631a33f412d26e4e)
interface __BaseEnv_Env {
	MEDIA: R2Bucket;
	DB: D1Database;
	LOADER: WorkerLoader;
	IMAGES: ImagesBinding;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ASSETS: Fetcher;
	EMDASH_SITE_URL: "https://www.smokycannabisco.com";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "EMDASH_SITE_URL">> {}
}
